# Generated by Django 3.2 on 2021-04-15 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import weather.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(default=weather.models.eventCodeGenerator, max_length=15, unique=True)),
                ('event_time', models.DateTimeField()),
                ('event_title', models.CharField(max_length=50, unique=True)),
                ('event_activity', models.TextField(max_length=50, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
