# Generated by Django 3.2 on 2021-04-18 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20210417_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_time',
        ),
        migrations.AddField(
            model_name='event',
            name='event_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 17, 18, 45, 850704)),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 17, 18, 45, 850704)),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
