# Generated by Django 3.2 on 2021-04-18 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20210418_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_activity',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 18, 15, 51, 771305)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 18, 15, 51, 771305)),
        ),
    ]
